# Generated by Django 3.2.7 on 2022-08-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('opened', models.CharField(max_length=200)),
                ('high', models.CharField(max_length=200)),
                ('low', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
                ('lastTradingDay', models.CharField(max_length=200)),
                ('previousClose', models.CharField(max_length=200)),
                ('change', models.CharField(max_length=200)),
                ('changePercent', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
