# Generated by Django 3.2.7 on 2022-09-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(db_index=True, default='any_name', max_length=200),
        ),
    ]
