# Generated by Django 3.2.7 on 2022-09-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_stock_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='code',
            new_name='symbol',
        ),
    ]
